// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ujOaYIa5k-5scT6TclNRaMhT7j0fEds',
    appId: '1:122146118053:android:5d47bf20d4521f05c3f04c',
    messagingSenderId: '122146118053',
    projectId: 'todo-app-riverpod-8ff02',
    storageBucket: 'todo-app-riverpod-8ff02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvZFz8g8ZnRbSeDR4LCZRAxqI_kzXhCwQ',
    appId: '1:122146118053:ios:1884fee9e45a3627c3f04c',
    messagingSenderId: '122146118053',
    projectId: 'todo-app-riverpod-8ff02',
    storageBucket: 'todo-app-riverpod-8ff02.appspot.com',
    iosClientId: '122146118053-rfk388gi6k9nqk57imj0n5l3c2kalfj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodTodoApp',
  );
}
